apiVersion: v1
kind: Service
metadata:
  name: corncobs-sus-website-svc
  namespace: challenges
  labels:
    app: corncobs-sus-website
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: corncobs-sus-website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corncobs-sus-website-svc
  namespace: challenges
  labels:
    app: corncobs-sus-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corncobs-sus-website
  template:
    metadata:
      labels:
        app: corncobs-sus-website
    spec:
      containers:
      - name: corncobs-sus-website
        image: gcr.io/mcps-hsf-316519/corncobs-sus-website:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: false
      imagePullSecrets:
      - name: regcred
