apiVersion: v1
kind: Service
metadata:
  name: fileshare-flask-svc
  namespace: challenges
  labels:
    app: fileshare-flask
spec:
  type: LoadBalancer
  ports:
  - port: 8002
    targetPort: 8000
    protocol: TCP
  selector:
    app: fileshare-flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileshare-flask-svc
  namespace: challenges
  labels:
    app: fileshare-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileshare-flask
  template:
    metadata:
      labels:
        app: fileshare-flask
    spec:
      containers:
      - name: fileshare-flask
        image: fileshare-flask-302680321
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
        securityContext:
          runAsUser: 0
      imagePullSecrets:
      - name: regcred
