apiVersion: v1
kind: Service
metadata:
  name: jekyll-blog-svc
  namespace: challenges
  labels:
    app: jekyll-blog
spec:
  type: LoadBalancer
  ports:
  - port: 8011
    targetPort: 80
    protocol: TCP
  selector:
    app: jekyll-blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jekyll-blog-svc
  namespace: challenges
  labels:
    app: jekyll-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jekyll-blog
  template:
    metadata:
      labels:
        app: jekyll-blog
    spec:
      containers:
      - name: jekyll-blog
        image: jekyll-blog-8793342933677
        ports:
        - containerPort: 80
        imagePullPolicy: Never
        securityContext:
          runAsUser: 0
      imagePullSecrets:
      - name: regcred
