apiVersion: v1
kind: Service
metadata:
  name: jekyll-blog-svc
  namespace: challenges
  labels:
    app: jekyll-blog
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: jekyll-blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jekyll-blog-svc
  namespace: challenges
  labels:
    app: jekyll-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jekyll-blog
  template:
    metadata:
      labels:
        app: jekyll-blog
    spec:
      containers:
      - name: jekyll-blog
        image: gcr.io/mcps-hsf-316519/jekyll-blog:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: false
      imagePullSecrets:
      - name: regcred
