apiVersion: v1
kind: Service
metadata:
  name: secret-chat-svc
  namespace: challenges
  labels:
    app: secret-chat
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: secret-chat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-chat-svc
  namespace: challenges
  labels:
    app: secret-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-chat
  template:
    metadata:
      labels:
        app: secret-chat
    spec:
      containers:
      - name: secret-chat
        image: gcr.io/mcps-hsf-316519/secret-chat:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: false
      imagePullSecrets:
      - name: regcred
