apiVersion: v1
kind: Service
metadata:
  name: secret-chat-svc
  namespace: challenges
  labels:
    app: secret-chat
spec:
  type: LoadBalancer
  ports:
  - port: 8006
    targetPort: 5000
    protocol: TCP
  selector:
    app: secret-chat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-chat-svc
  namespace: challenges
  labels:
    app: secret-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-chat
  template:
    metadata:
      labels:
        app: secret-chat
    spec:
      containers:
      - name: secret-chat
        image: secret_chat-8791128532449
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
        securityContext:
          runAsUser: 0
      imagePullSecrets:
      - name: regcred
