apiVersion: v1
kind: Service
metadata:
  name: twitter-flask-svc
  namespace: challenges
  labels:
    app: twitter-flask
spec:
  type: LoadBalancer
  ports:
  - port: 8013
    targetPort: 5000
    protocol: TCP
  selector:
    app: twitter-flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-flask-svc
  namespace: challenges
  labels:
    app: twitter-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-flask
  template:
    metadata:
      labels:
        app: twitter-flask
    spec:
      containers:
      - name: twitter-flask
        image: twitter-8793343616898
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
        securityContext:
          runAsUser: 0
      imagePullSecrets:
      - name: regcred
