apiVersion: v1
kind: Service
metadata:
  name: chal-host-svc
  namespace: challenges
  labels:
    app: chal-host
spec:
  type: LoadBalancer
  ports:
  - port: 8001
    targetPort: 80
    protocol: TCP
  selector:
    app: chal-host
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chal-host-svc
  namespace: challenges
  labels:
    app: chal-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chal-host
  template:
    metadata:
      labels:
        app: chal-host
    spec:
      containers:
      - name: chal-host
        image: chal-host:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
      imagePullSecrets:
      - name: regcred
