apiVersion: v1
kind: Service
metadata:
  name: facebook-django-svc
  namespace: challenges
  labels:
    app: facebook-django
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: facebook-django
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-django-svc
  namespace: challenges
  labels:
    app: facebook-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facebook-django
  template:
    metadata:
      labels:
        app: facebook-django
    spec:
      containers:
      - name: facebook-django
        image: facebook-django:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
      imagePullSecrets:
      - name: regcred
