apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctfd-pv-uploads
  namespace: challenges
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/uploads"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctfd-pv-logs
  namespace: challenges
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-pv-uploads-claim
  namespace: challenges
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-pv-logs-claim
  namespace: challenges
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
