apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shell-ingress
  namespace: shells
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
  - host: test.shells.mcpshsf.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: shell-1234-svc
            port:
              number: 80