apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: challenge-ingress
  namespace: challenges
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
  - host: fesbuc.chals.mcpshsf.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: fesbuc-svc
            port:
              number: 80
  - host: fred-shared-server.chals.mcpshsf.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: fred-shared-server-svc
            port:
              number: 80
  - host: chal-host.chals.mcpshsf.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: chal-host-svc
            port:
              number: 80
