apiVersion: v1
kind: Service
metadata:
  name: inn-website-svc
  namespace: challenges
  labels:
    app: inn-website
spec:
  type: LoadBalancer
  ports:
  - port: 8004
    targetPort: 80
    protocol: TCP
  selector:
    app: inn-website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inn-website-svc
  namespace: challenges
  labels:
    app: inn-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inn-website
  template:
    metadata:
      labels:
        app: inn-website
    spec:
      containers:
      - name: inn-website
        image: static_site-8737150909203
        ports:
        - containerPort: 80
        imagePullPolicy: Never
        securityContext:
          runAsUser: 0
      imagePullSecrets:
      - name: regcred
