apiVersion: v1
kind: Service
metadata:
  name: robotschallenge-svc
  namespace: challenges
  labels:
    app: robotschallenge
spec:
  type: LoadBalancer
  ports:
  - port: 8001
    targetPort: 80
    protocol: TCP
  selector:
    app: robotschallenge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robotschallenge-svc
  namespace: challenges
  labels:
    app: robotschallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robotschallenge
  template:
    metadata:
      labels:
        app: robotschallenge
    spec:
      containers:
      - name: robotschallenge
        image: robots_txt-314935233
        ports:
        - containerPort: 80
        imagePullPolicy: Never
        securityContext:
          runAsUser: 0
      imagePullSecrets:
      - name: regcred
